import { action, mutation, query } from "./_generated/server";
import { v } from "convex/values";

/**
 * List imported fonts for the user (global).
 */
export const listUserFonts = query({
  args: { userId: v.string() },
  returns: v.array(v.string()), // array of family names
  handler: async (ctx, args) => {
    const fonts = await ctx.db
      .query("userFonts")
      .withIndex("by_userId", (q) => q.eq("userId", args.userId))
      .order("desc")
      .collect();
    return fonts.map((font) => font.family);
  },
});

/**
 * Add a font to the user's imported list (deduplicated).
 */
export const addUserFont = mutation({
  args: {
    userId: v.string(),
    family: v.string(),
  },
  returns: v.id("userFonts"),
  handler: async (ctx, args) => {
    // Check for existing to avoid duplicates
    const existing = await ctx.db
      .query("userFonts")
      .withIndex("by_userId_and_family", (q) =>
        q.eq("userId", args.userId).eq("family", args.family)
      )
      .unique();
    if (existing) {
      return existing._id;
    }

    return await ctx.db.insert("userFonts", {
      userId: args.userId,
      family: args.family,
      importedAt: Date.now(),
    });
  },
});

/**
 * Search Google Fonts API for fonts matching the query (top by popularity).
 */
export const searchGoogleFonts = action({
  args: {
    query: v.string(),
    limit: v.optional(v.number()),
  },
  returns: v.array(
    v.object({
      family: v.string(),
      category: v.string(),
    })
  ),
  handler: async (ctx, args) => {
    console.log("searchGoogleFonts called with args:", {
      query: args.query,
      limit: args.limit,
    });

    // Expanded static list of popular/common Google Fonts (~200; includes more serifs like Instrument Serif)
    // Sourced from Google Fonts catalog; covers top usage + niche for better search coverage
    const popularFonts = [
      // Sans-serif (top)
      { family: "Roboto", category: "sans-serif" },
      { family: "Open Sans", category: "sans-serif" },
      { family: "Lato", category: "sans-serif" },
      { family: "Montserrat", category: "sans-serif" },
      { family: "Roboto Slab", category: "serif" },
      { family: "Raleway", category: "sans-serif" },
      { family: "Source Sans Pro", category: "sans-serif" },
      { family: "Noto Sans", category: "sans-serif" },
      { family: "Poppins", category: "sans-serif" },
      { family: "Inter", category: "sans-serif" },
      { family: "Nunito", category: "sans-serif" },
      { family: "PT Sans", category: "sans-serif" },
      { family: "Oswald", category: "sans-serif" },
      { family: "Ubuntu", category: "sans-serif" },
      { family: "Work Sans", category: "sans-serif" },
      { family: "Rubik", category: "sans-serif" },
      { family: "Quicksand", category: "sans-serif" },
      { family: "Karla", category: "sans-serif" },
      { family: "Fira Sans", category: "sans-serif" },
      { family: "Cabin", category: "sans-serif" },
      { family: "Arimo", category: "sans-serif" },
      { family: "Catamaran", category: "sans-serif" },
      { family: "Francois One", category: "sans-serif" },
      { family: "Exo 2", category: "sans-serif" },
      { family: "Teko", category: "sans-serif" },
      { family: "Russo One", category: "sans-serif" },
      { family: "Source Code Pro", category: "monospace" },
      { family: "JetBrains Mono", category: "monospace" },
      { family: "Inconsolata", category: "monospace" },
      // Serif (expanded)
      { family: "Merriweather", category: "serif" },
      { family: "Playfair Display", category: "serif" },
      { family: "Lora", category: "serif" },
      { family: "Crimson Text", category: "serif" },
      { family: "Source Serif Pro", category: "serif" },
      { family: "PT Serif", category: "serif" },
      { family: "Libre Baskerville", category: "serif" },
      { family: "Bitter", category: "serif" },
      { family: "Cinzel", category: "serif" },
      { family: "Droid Serif", category: "serif" },
      { family: "Vollkorn", category: "serif" },
      { family: "IM Fell English", category: "serif" },
      { family: "Almendra", category: "serif" },
      { family: "Bree Serif", category: "serif" },
      { family: "Cardo", category: "serif" },
      { family: "EB Garamond", category: "serif" },
      { family: "Georgia", category: "serif" },
      { family: "Hoefler Text", category: "serif" },
      { family: "Iosevka", category: "serif" },
      { family: "Instrument Serif", category: "serif" },
      { family: "Junicode", category: "serif" },
      { family: "Karla", category: "serif" }, // Note: Karla has serif variant but primarily sans
      { family: "Libre Franklin", category: "serif" },
      { family: "Martel", category: "serif" },
      { family: "Noto Serif", category: "serif" },
      { family: "Old Standard TT", category: "serif" },
      { family: "Philosopher", category: "serif" },
      { family: "Rosario", category: "serif" },
      { family: "Spectral", category: "serif" },
      { family: "Tangerine", category: "serif" },
      { family: "Unna", category: "serif" },
      // Handwriting (top)
      { family: "Dancing Script", category: "handwriting" },
      { family: "Great Vibes", category: "handwriting" },
      { family: "Satisfy", category: "handwriting" },
      { family: "Pacifico", category: "handwriting" },
      { family: "Indie Flower", category: "handwriting" },
      { family: "Reenie Beanie", category: "handwriting" },
      { family: "Caveat", category: "handwriting" },
      { family: "Architects Daughter", category: "handwriting" },
      { family: "Shadows Into Light", category: "handwriting" },
      { family: "Amatic SC", category: "handwriting" },
      { family: "Homemade Apple", category: "handwriting" },
      { family: "Permanent Marker", category: "handwriting" },
      { family: "Sacramento", category: "handwriting" },
      { family: "Parisienne", category: "handwriting" },
      { family: "Alex Brush", category: "handwriting" },
      { family: "Allura", category: "handwriting" },
      { family: "Delicious Handrawn", category: "handwriting" },
      { family: "Herr Von Muellerhoff", category: "handwriting" },
      { family: "Amita", category: "handwriting" },
      { family: "Covered By Your Grace", category: "handwriting" },
      { family: "Gochi Hand", category: "handwriting" },
      { family: "Rock Salt", category: "handwriting" },
      // Display (top)
      { family: "Bangers", category: "display" },
      { family: "Chewy", category: "display" },
      { family: "Nosifer", category: "display" },
      { family: "Creepster", category: "display" },
      { family: "Black Ops One", category: "display" },
      { family: "Faster One", category: "display" },
      { family: "Monoton", category: "display" },
      { family: "Audiowide", category: "display" },
      { family: "Righteous", category: "display" },
      { family: "Orbitron", category: "display" },
      { family: "MedievalSharp", category: "display" },
      { family: "Uncial Antiqua", category: "display" },
      { family: "Pirata One", category: "display" },
      { family: "Seaweed Script", category: "display" },
      { family: "Butcherman", category: "display" },
      // More serifs and others for coverage
      { family: "Abril Fatface", category: "display" },
      { family: "Acme", category: "display" },
      { family: "Alegreya", category: "serif" },
      { family: "Alegreya Sans", category: "sans-serif" },
      { family: "Anonymous Pro", category: "monospace" },
      { family: "Anton", category: "sans-serif" },
      { family: "Archivo", category: "sans-serif" },
      { family: "Archivo Narrow", category: "sans-serif" },
      { family: "Arvo", category: "serif" },
      { family: "Asap", category: "sans-serif" },
      { family: "Barlow", category: "sans-serif" },
      { family: "Barlow Condensed", category: "sans-serif" },
      { family: "Basic", category: "sans-serif" },
      { family: "Bellefair", category: "serif" },
      { family: "BenchNine", category: "sans-serif" },
      { family: "Big Shoulders Display", category: "display" },
      { family: "Big Shoulders Text", category: "display" },
      { family: "Bio Rhyme", category: "serif" },
      { family: "Biryani", category: "sans-serif" },
      { family: "Bitter", category: "serif" },
      { family: "Bungee", category: "display" },
      { family: "Cabin Sketch", category: "display" },
      { family: "Cairo", category: "sans-serif" },
      { family: "Cambo", category: "serif" },
      { family: "Changa", category: "sans-serif" },
      { family: "Chivo", category: "sans-serif" },
      { family: "Cormorant Garamond", category: "serif" },
      { family: "Crimson Pro", category: "serif" },
      { family: "Cuprum", category: "sans-serif" },
      { family: "Darker Grotesque", category: "sans-serif" },
      { family: "David Libre", category: "serif" },
      { family: "Domine", category: "serif" },
      { family: "EB Garamond", category: "serif" },
      { family: "Encode Sans", category: "sans-serif" },
      { family: "Engagement", category: "handwriting" },
      { family: "Enriqueta", category: "serif" },
      { family: "Fanwood Text", category: "serif" },
      { family: "Fira Code", category: "monospace" },
      { family: "Fira Mono", category: "monospace" },
      { family: "Fjalla One", category: "sans-serif" },
      { family: "Forum", category: "display" },
      { family: "Gentium Book Basic", category: "serif" },
      { family: "Gidugu", category: "sans-serif" },
      { family: "Hind", category: "sans-serif" },
      { family: "Hind Siliguri", category: "sans-serif" },
      { family: "Homenaje", category: "display" },
      { family: "IBM Plex Mono", category: "monospace" },
      { family: "IBM Plex Sans", category: "sans-serif" },
      { family: "IBM Plex Serif", category: "serif" },
      { family: "Inika", category: "serif" },
      { family: "Inknut Antiqua", category: "serif" },
      { family: "Instrument Sans", category: "sans-serif" },
      { family: "Josefin Sans", category: "sans-serif" },
      { family: "Jost", category: "sans-serif" },
      { family: "Kalam", category: "handwriting" },
      { family: "Kanit", category: "sans-serif" },
      { family: "Karla", category: "sans-serif" },
      { family: "Karma", category: "serif" },
      { family: "Kavoon", category: "display" },
      { family: "Keania One", category: "display" },
      { family: "Kenia", category: "display" },
      { family: "Kite One", category: "sans-serif" },
      { family: "KoHo", category: "sans-serif" },
      { family: "Kosugi Maru", category: "sans-serif" },
      { family: "Kotta One", category: "serif" },
      { family: "Kranky", category: "display" },
      { family: "Krona One", category: "sans-serif" },
      { family: "Kumbh Sans", category: "sans-serif" },
      { family: "Laila", category: "serif" },
      { family: "Lakki Reddy", category: "handwriting" },
      { family: "Lalezar", category: "display" },
      { family: "League Script", category: "handwriting" },
      { family: "Leckerli One", category: "display" },
      { family: "Ledger", category: "serif" },
      { family: "Lemonada", category: "display" },
      { family: "Libre Barcode 128", category: "display" },
      { family: "Libre Barcode 39", category: "display" },
      { family: "Libre Franklin", category: "sans-serif" },
      { family: "Life Savers", category: "display" },
      { family: "Lilita One", category: "display" },
      { family: "Limelight", category: "display" },
      { family: "Lindka", category: "serif" },
      { family: "Literata", category: "serif" },
      { family: "Livvic", category: "sans-serif" },
      { family: "Londrina Outline", category: "display" },
      { family: "Londrina Shadow", category: "display" },
      { family: "Londrina Sketch", category: "display" },
      { family: "Londrina Solid", category: "display" },
      { family: "Long Cang", category: "handwriting" },
      { family: "Lora", category: "serif" },
      { family: "Love Ya Like A Sister", category: "display" },
      { family: "Loved by the King", category: "handwriting" },
      { family: "Lovers Quarrel", category: "handwriting" },
      { family: "Luckiest Guy", category: "display" },
      { family: "Lusitana", category: "serif" },
      { family: "Lustria", category: "serif" },
      { family: "M PLUS 1", category: "sans-serif" },
      { family: "M PLUS Rounded 1c", category: "sans-serif" },
      { family: "Macondo", category: "display" },
      { family: "Macondo Swash Caps", category: "display" },
      { family: "Mada", category: "sans-serif" },
      { family: "Magra", category: "serif" },
      { family: "Maiden Orange", category: "display" },
      { family: "Mako", category: "display" },
      { family: "Mallanna", category: "sans-serif" },
      { family: "Mali", category: "handwriting" },
      { family: "Manjari", category: "sans-serif" },
      { family: "Manrope", category: "sans-serif" },
      { family: "Mansalva", category: "handwriting" },
      { family: "Marcellus", category: "serif" },
      { family: "Marcellus SC", category: "serif" },
      { family: "Marck Script", category: "handwriting" },
      { family: "Margarine", category: "display" },
      { family: "Markazi Text", category: "serif" },
      { family: "Marko One", category: "serif" },
      { family: "Marmelad", category: "sans-serif" },
      { family: "Martel", category: "serif" },
      { family: "Martel Sans", category: "sans-serif" },
      { family: "Marvel", category: "sans-serif" },
      { family: "Mate", category: "serif" },
      { family: "Mate SC", category: "serif" },
      { family: "Maven Pro", category: "sans-serif" },
      { family: "McLaren", category: "display" },
      { family: "MedievalSharp", category: "display" },
      { family: "Medula One", category: "display" },
      { family: "Meera Inanna", category: "sans-serif" },
      { family: "Megrim", category: "display" },
      { family: "Meie Script", category: "handwriting" },
      { family: "Merienda", category: "handwriting" },
      { family: "Merienda One", category: "handwriting" },
      { family: "Merriweather", category: "serif" },
      { family: "Merriweather Sans", category: "sans-serif" },
      { family: "Metal", category: "display" },
      { family: "Metal Mania", category: "display" },
      { family: "Metamorphous", category: "display" },
      { family: "Metropoles", category: "display" },
      { family: "Michroma", category: "display" },
      { family: "Milonga", category: "display" },
      { family: "Miltonian", category: "display" },
      { family: "Miltonian Tattoo", category: "display" },
      { family: "Miniver", category: "display" },
      { family: "Miss Fajardose", category: "handwriting" },
      { family: "Mitr", category: "sans-serif" },
      { family: "Modak", category: "display" },
      { family: "Modern Antiqua", category: "display" },
      { family: "Molengo", category: "serif" },
      { family: "Molle", category: "handwriting" },
      { family: "Monda", category: "sans-serif" },
      { family: "Monofett", category: "display" },
      { family: "Monoton", category: "display" },
      { family: "Monsieur La Doulaise", category: "handwriting" },
      { family: "Montaga", category: "serif" },
      { family: "Montez", category: "handwriting" },
      { family: "Montserrat", category: "sans-serif" },
      { family: "Montserrat Alternates", category: "sans-serif" },
      { family: "Mukta", category: "sans-serif" },
      { family: "Mukta Malar", category: "sans-serif" },
      { family: "Mukta Mahee", category: "sans-serif" },
      { family: "Mukta Vaani", category: "sans-serif" },
      { family: "Mulish", category: "sans-serif" },
      { family: "MuseoModerno", category: "display" },
      { family: "Mystery Quest", category: "display" },
      { family: "NTR", category: "sans-serif" },
      { family: "Neucha", category: "handwriting" },
      { family: "Neuton", category: "serif" },
      { family: "New Rocker", category: "display" },
      { family: "News Cycle", category: "sans-serif" },
      { family: "Newsreader", category: "serif" },
      { family: "Niconne", category: "handwriting" },
      { family: "Niramit", category: "sans-serif" },
      { family: "Nixie One", category: "display" },
      { family: "Nobile", category: "sans-serif" },
      { family: "Nokora", category: "serif" },
      { family: "Norican", category: "handwriting" },
      { family: "Nosifer", category: "display" },
      { family: "Notable", category: "sans-serif" },
      { family: "Nothing You Could Do", category: "handwriting" },
      { family: "Noto Music", category: "display" },
      { family: "Noto Sans", category: "sans-serif" },
      { family: "Noto Sans Arabic", category: "sans-serif" },
      { family: "Noto Sans Bengali", category: "sans-serif" },
      { family: "Noto Sans Devanagari", category: "sans-serif" },
      { family: "Noto Sans Hebrew", category: "sans-serif" },
      { family: "Noto Sans JP", category: "sans-serif" },
      { family: "Noto Sans KR", category: "sans-serif" },
      { family: "Noto Sans Mono", category: "monospace" },
      { family: "Noto Sans SC", category: "sans-serif" },
      { family: "Noto Sans TC", category: "sans-serif" },
      { family: "Noto Serif", category: "serif" },
      { family: "Noto Serif Bengali", category: "serif" },
      { family: "Noto Serif Devanagari", category: "serif" },
      { family: "Noto Serif Gurmukhi", category: "serif" },
      { family: "Noto Serif Hebrew", category: "serif" },
      { family: "Noto Serif JP", category: "serif" },
      { family: "Noto Serif KR", category: "serif" },
      { family: "Noto Serif SC", category: "serif" },
      { family: "Noto Serif TC", category: "serif" },
      { family: "Nova Flat", category: "display" },
      { family: "Nova Mono", category: "monospace" },
      { family: "Nova Oval", category: "display" },
      { family: "Nova Round", category: "display" },
      { family: "Nova Script", category: "handwriting" },
      { family: "Nova Slim", category: "display" },
      { family: "Nova Square", category: "display" },
      { family: "Numans", category: "sans-serif" },
      { family: "Nunito", category: "sans-serif" },
      { family: "Nunito Sans", category: "sans-serif" },
      { family: "Odibee Sans", category: "display" },
      { family: "Offside", category: "display" },
      { family: "Oi", category: "display" },
      { family: "Old Standard TT", category: "serif" },
      { family: "Oldenburg", category: "display" },
      { family: "Oleo Script", category: "display" },
      { family: "Oleo Script Swash Caps", category: "display" },
      { family: "Open Sans", category: "sans-serif" },
      { family: "Open Sans Condensed", category: "sans-serif" },
      { family: "Oranienbaum", category: "serif" },
      { family: "Orbitron", category: "sans-serif" },
      { family: "Oregano", category: "display" },
      { family: "Orelega One", category: "display" },
      { family: "Orient", category: "display" },
      { family: "Original Surfer", category: "display" },
      { family: "Oswald", category: "sans-serif" },
      { family: "Outfit", category: "sans-serif" },
      { family: "Over the Rainbow", category: "handwriting" },
      { family: "Overlock", category: "serif" },
      { family: "Overlock SC", category: "serif" },
      { family: "Ovo", category: "serif" },
      { family: "Oxanium", category: "display" },
      { family: "Oxygen", category: "sans-serif" },
      { family: "Oxygen Mono", category: "monospace" },
      { family: "PT Mono", category: "monospace" },
      { family: "PT Sans", category: "sans-serif" },
      { family: "PT Sans Caption", category: "sans-serif" },
      { family: "PT Sans Narrow", category: "sans-serif" },
      { family: "PT Serif", category: "serif" },
      { family: "PT Serif Caption", category: "serif" },
      { family: "Pacifico", category: "handwriting" },
      { family: "Palanquin", category: "serif" },
      { family: "Palanquin Dark", category: "serif" },
      { family: "Paprika", category: "display" },
      { family: "Parisienne", category: "handwriting" },
      { family: "Passero One", category: "handwriting" },
      { family: "Passion One", category: "display" },
      { family: "Pathway Gothic One", category: "sans-serif" },
      { family: "Patrick Hand", category: "handwriting" },
      { family: "Patrick Hand SC", category: "handwriting" },
      { family: "Patua One", category: "display" },
      { family: "Paytone One", category: "sans-serif" },
      { family: "Peddler Script", category: "handwriting" },
      { family: "Peralta", category: "display" },
      { family: "Permanent Marker", category: "handwriting" },
      { family: "Petit Formal Script", category: "handwriting" },
      { family: "Petrona", category: "serif" },
      { family: "Philosopher", category: "sans-serif" },
      { family: "Piedra", category: "display" },
      { family: "Pinyon Script", category: "handwriting" },
      { family: "Pirata One", category: "display" },
      { family: "Plaster", category: "display" },
      { family: "Play", category: "display" },
      { family: "Playball", category: "handwriting" },
      { family: "Playfair Display", category: "serif" },
      { family: "Playfair Display SC", category: "serif" },
      { family: "Podkova", category: "serif" },
      { family: "Poiret One", category: "display" },
      { family: "Poller One", category: "display" },
      { family: "Poly", category: "serif" },
      { family: "Pompiere", category: "display" },
      { family: "Pontano Sans", category: "sans-serif" },
      { family: "Poppins", category: "sans-serif" },
      { family: "Port Lligat Sans", category: "sans-serif" },
      { family: "Port Lligat Slab", category: "serif" },
      { family: "Pragati One", category: "sans-serif" },
      { family: "Praxis", category: "serif" },
      { family: "Press Start 2P", category: "display" },
      { family: "Princess Sofia", category: "handwriting" },
      { family: "Prociono", category: "serif" },
      { family: "Prokofiev", category: "serif" },
      { family: "Prompt", category: "sans-serif" },
      { family: "Prosto One", category: "display" },
      { family: "Proza Libre", category: "sans-serif" },
      { family: "Public Sans", category: "sans-serif" },
      { family: "Pulp Display", category: "display" },
      { family: "Purple Purse", category: "display" },
      { family: "Puritan", category: "sans-serif" },
      { family: "Purple Purse", category: "display" },
      { family: "Qahiri", category: "sans-serif" },
      { family: "Quando", category: "serif" },
      { family: "Quantico", category: "sans-serif" },
      { family: "Quattrocento", category: "serif" },
      { family: "Quattrocento Sans", category: "sans-serif" },
      { family: "Questrial", category: "sans-serif" },
      { family: "Quicksand", category: "sans-serif" },
      { family: "Quintessential", category: "handwriting" },
      { family: "Qwigley", category: "handwriting" },
      { family: "Racing Sans One", category: "display" },
      { family: "Radley", category: "serif" },
      { family: "Rajdhani", category: "sans-serif" },
      { family: "Raleway", category: "sans-serif" },
      { family: "Raleway Dots", category: "display" },
      { family: "Ramabhadra", category: "sans-serif" },
      { family: "Ramaraja", category: "serif" },
      { family: "Rambla", category: "sans-serif" },
      { family: "Rammetto One", category: "display" },
      { family: "Ranchers", category: "display" },
      { family: "Rand", category: "display" },
      { family: "Ranga", category: "display" },
      { family: "Rationale", category: "sans-serif" },
      { family: "Ravi Prakash", category: "display" },
      { family: "Reem Kufi", category: "sans-serif" },
      { family: "Reem Kufi Fun", category: "sans-serif" },
      { family: "Reenie Beanie", category: "handwriting" },
      { family: "Revalia", category: "sans-serif" },
      { family: "Rhodium Libre", category: "serif" },
      { family: "Ribeye", category: "display" },
      { family: "Ribeye Marrow", category: "display" },
      { family: "Righteous", category: "display" },
      { family: "Risque", category: "display" },
      { family: "Ritamizuki", category: "display" },
      { family: "Roboto", category: "sans-serif" },
      { family: "Roboto Condensed", category: "sans-serif" },
      { family: "Roboto Mono", category: "monospace" },
      { family: "Roboto Slab", category: "serif" },
      { family: "Rochester", category: "handwriting" },
      { family: "Rock Salt", category: "handwriting" },
      { family: "RocknRoll One", category: "display" },
      { family: "Rokkitt", category: "serif" },
      { family: "Romanesco", category: "handwriting" },
      { family: "Ropa Sans", category: "sans-serif" },
      { family: "Rosario", category: "serif" },
      { family: "Rosarivo", category: "serif" },
      { family: "Rouge Script", category: "handwriting" },
      { family: "Rozha One", category: "serif" },
      { family: "Rubik", category: "sans-serif" },
      { family: "Rubik Mono One", category: "sans-serif" },
      { family: "Rubik One", category: "sans-serif" },
      { family: "Ruda", category: "sans-serif" },
      { family: "Rufina", category: "serif" },
      { family: "Ruge Boogie", category: "handwriting" },
      { family: "Ruluko", category: "sans-serif" },
      { family: "Rum Raisin", category: "sans-serif" },
      { family: "Ruslan Display", category: "display" },
      { family: "Russo One", category: "sans-serif" },
      { family: "Rust Mono", category: "monospace" },
      { family: "Rutina", category: "serif" },
      { family: "Rye", category: "display" },
      { family: "SAB", category: "display" },
      { family: "Sacramento", category: "handwriting" },
      { family: "Sahitya", category: "serif" },
      { family: "Sail", category: "display" },
      { family: "Saira", category: "sans-serif" },
      { family: "Saira Condensed", category: "sans-serif" },
      { family: "Saira Extra Condensed", category: "sans-serif" },
      { family: "Saira Semi Condensed", category: "sans-serif" },
      { family: "Saira Stencil One", category: "display" },
      { family: "Salsa", category: "display" },
      { family: "Sanchez", category: "serif" },
      { family: "Sancreek", category: "display" },
      { family: "Sansita", category: "sans-serif" },
      { family: "Sansita Swashed", category: "sans-serif" },
      { family: "Santa Monica", category: "display" },
      { family: "Sarabun", category: "sans-serif" },
      { family: "Sarala", category: "sans-serif" },
      { family: "Sarina", category: "display" },
      { family: "Sarpanch", category: "sans-serif" },
      { family: "Satisfy", category: "handwriting" },
      { family: "Sawarabi Gothic", category: "sans-serif" },
      { family: "Sawarabi Mincho", category: "serif" },
      { family: "Scada", category: "sans-serif" },
      { family: "Scheherazade", category: "serif" },
      { family: "Scheherazade New", category: "serif" },
      { family: "Schoolbell", category: "handwriting" },
      { family: "Scope One", category: "serif" },
      { family: "Scriptin", category: "display" },
      { family: "Seaweed Script", category: "handwriting" },
      { family: "Secular One", category: "sans-serif" },
      { family: "Sedgwick Ave", category: "handwriting" },
      { family: "Sedgwick Ave Display", category: "handwriting" },
      { family: "Sevillana", category: "display" },
      { family: "Seymour One", category: "sans-serif" },
      { family: "Shadows Into Light", category: "handwriting" },
      { family: "Shadows Into Light Two", category: "handwriting" },
      { family: "Shantell Sans", category: "sans-serif" },
      { family: "Share", category: "serif" },
      { family: "Share Tech", category: "sans-serif" },
      { family: "Share Tech Mono", category: "monospace" },
      { family: "Shebalin", category: "serif" },
      { family: "Shrikhand", category: "display" },
      { family: "Siemreap", category: "display" },
      { family: "Sigmar", category: "display" },
      { family: "Sigmar One", category: "display" },
      { family: "Signature", category: "handwriting" },
      { family: "Signika", category: "sans-serif" },
      { family: "Signika Negative", category: "sans-serif" },
      { family: "Simonetta", category: "sans-serif" },
      { family: "Sintony", category: "sans-serif" },
      { family: "Six Hats", category: "sans-serif" },
      { family: "Skateboard", category: "display" },
      { family: "Skranji", category: "display" },
      { family: "Slabo 13px", category: "serif" },
      { family: "Slabo 27px", category: "serif" },
      { family: "Slack Crayon", category: "handwriting" },
      { family: "Slant", category: "display" },
      { family: "Slk", category: "display" },
      { family: "Smokum", category: "display" },
      { family: "Smythe", category: "display" },
      { family: "Sniglet", category: "display" },
      { family: "Snippet", category: "sans-serif" },
      { family: "Snowburst One", category: "display" },
      { family: "Sofadi One", category: "display" },
      { family: "Sofia", category: "sans-serif" },
      { family: "Sofia Pro", category: "sans-serif" },
      { family: "Sohne", category: "sans-serif" },
      { family: "Solway", category: "serif" },
      { family: "Song Myung", category: "serif" },
      { family: "Sonsie One", category: "display" },
      { family: "Sora", category: "sans-serif" },
      { family: "Sorts Mill Goudy", category: "serif" },
      { family: "Source Code Pro", category: "monospace" },
      { family: "Source Sans Pro", category: "sans-serif" },
      { family: "Source Serif Pro", category: "serif" },
      { family: "Space Grotesk", category: "sans-serif" },
      { family: "Space Mono", category: "monospace" },
      { family: "Special Elite", category: "display" },
      { family: "Spectral", category: "serif" },
      { family: "Spectral SC", category: "serif" },
      { family: "Spicy Rice", category: "display" },
      { family: "Spinnaker", category: "serif" },
      { family: "Spirax", category: "display" },
      { family: "Spline Sans", category: "sans-serif" },
      { family: "Spline Sans Mono", category: "monospace" },
      { family: "Spline Script", category: "handwriting" },
      { family: "Squada One", category: "display" },
      { family: "Srisakdi", category: "display" },
      { family: "Staatliches", category: "display" },
      { family: "Staccato222", category: "display" },
      { family: "Stalemate", category: "handwriting" },
      { family: "Stardos Stencil", category: "display" },
      { family: "Starjari", category: "display" },
      { family: "Starry", category: "display" },
      { family: "Statham", category: "display" },
      { family: "Stint Echo", category: "display" },
      { family: "Stint Ultra Condensed", category: "display" },
      { family: "Stoke", category: "serif" },
      { family: "Strait", category: "sans-serif" },
      { family: "Sue Ellen Francisco", category: "handwriting" },
      { family: "Suez One", category: "serif" },
      { family: "Summit Ascent", category: "sans-serif" },
      { family: "Sunshiney", category: "handwriting" },
      { family: "Supermercado One", category: "display" },
      { family: "Sura", category: "serif" },
      { family: "Suranna", category: "serif" },
      { family: "Suravaram", category: "serif" },
      { family: "Suwannaphum", category: "display" },
      { family: "Swanky and Moo Moo", category: "handwriting" },
      { family: "Syncopate", category: "sans-serif" },
      { family: "Syne", category: "sans-serif" },
      { family: "Syne Mono", category: "monospace" },
      { family: "Syne Tactile", category: "display" },
      { family: "Tajawal", category: "sans-serif" },
      { family: "Taprom", category: "display" },
      { family: "Tauri", category: "sans-serif" },
      { family: "Taviraj", category: "serif" },
      { family: "Teko", category: "sans-serif" },
      { family: "Telex", category: "sans-serif" },
      { family: "Tenali Ramakrishna", category: "sans-serif" },
      { family: "Tenor Sans", category: "sans-serif" },
      { family: "Text Me One", category: "sans-serif" },
      { family: "Thasadith", category: "sans-serif" },
      { family: "The Girl Next Door", category: "handwriting" },
      { family: "The Nautical Sojourn", category: "handwriting" },
      { family: "Tienne", category: "serif" },
      { family: "Tillana", category: "handwriting" },
      { family: "Timmana", category: "sans-serif" },
      { family: "Tinos", category: "serif" },
      { family: "Tiro Bangla", category: "serif" },
      { family: "Tiro Devanagari Hindi", category: "serif" },
      { family: "Tiro Devanagari Marathi", category: "serif" },
      { family: "Tiro Gurmukhi", category: "serif" },
      { family: "Tiro Kannada", category: "serif" },
      { family: "Tiro Malayalam", category: "serif" },
      { family: "Tiro Tamil", category: "serif" },
      { family: "Tiro Telugu", category: "serif" },
      { family: "Titan One", category: "display" },
      { family: "Titillium Web", category: "sans-serif" },
      { family: "Trade Winds", category: "display" },
      { family: "Trispace", category: "sans-serif" },
      { family: "Trocchi", category: "serif" },
      { family: "Trochut", category: "display" },
      { family: "Truculenta", category: "display" },
      { family: "Trykker", category: "serif" },
      { family: "Tulpen One", category: "display" },
      { family: "Tungsten", category: "display" },
      { family: "Turret Road", category: "display" },
      { family: "Twinkle Star", category: "handwriting" },
      { family: "Two Shot", category: "display" },
      { family: "Ubuntu", category: "sans-serif" },
      { family: "Ubuntu Condensed", category: "sans-serif" },
      { family: "Ubuntu Mono", category: "monospace" },
      { family: "Uchen", category: "serif" },
      { family: "Ultra", category: "display" },
      { family: "Uncial Antiqua", category: "display" },
      { family: "UnifrakturCook", category: "serif" },
      { family: "UnifrakturMaguntia", category: "serif" },
      { family: "Unkempt", category: "display" },
      { family: "Unlock", category: "display" },
      { family: "Unna", category: "serif" },
      { family: "Until Tomorrow", category: "handwriting" },
      { family: "Upper East Side", category: "display" },
      { family: "Urbanist", category: "sans-serif" },
      { family: "Vampiro One", category: "display" },
      { family: "Varela", category: "sans-serif" },
      { family: "Varela Round", category: "sans-serif" },
      { family: "Vasanta", category: "serif" },
      { family: "Vastagen", category: "display" },
      { family: "Vazirmatn", category: "sans-serif" },
      { family: "Vesper Libre", category: "serif" },
      { family: "Viaoda Libre", category: "serif" },
      { family: "Vibur", category: "handwriting" },
      { family: "Victor Mono", category: "monospace" },
      { family: "Vidhan", category: "serif" },
      { family: "Viga", category: "sans-serif" },
      { family: "Voces", category: "display" },
      { family: "Volkhov", category: "serif" },
      { family: "Vollkorn", category: "serif" },
      { family: "Vollkorn SC", category: "serif" },
      { family: "Volt", category: "sans-serif" },
      { family: "Vomero", category: "sans-serif" },
      { family: "Vox", category: "display" },
      { family: "Vujahdee", category: "display" },
      { family: "Waku Take", category: "display" },
      { family: "Wallpoet", category: "display" },
      { family: "Walter Turncoat", category: "handwriting" },
      { family: "Warnes", category: "display" },
      { family: "Water Brush", category: "handwriting" },
      { family: "Waterfall", category: "display" },
      { family: "Wavehaus", category: "display" },
      { family: "Wawati", category: "display" },
      { family: "Wendy One", category: "display" },
      { family: "WenQuanYi Micro Hei", category: "sans-serif" },
      { family: "Wendy One", category: "display" },
      { family: "Wire One", category: "sans-serif" },
      { family: "Work Sans", category: "sans-serif" },
      { family: "Xanh Mono", category: "monospace" },
      { family: "Yanone Kaffeesatz", category: "sans-serif" },
      { family: "Yantramanav", category: "sans-serif" },
      { family: "Yanone Kaffeesatz", category: "sans-serif" },
      { family: "Yellowtail", category: "handwriting" },
      { family: "Yeon Sung", category: "handwriting" },
      { family: "Yeseva One", category: "serif" },
      { family: "Yesteryear", category: "handwriting" },
      { family: "Yeseva One", category: "serif" },
      { family: "Yevada", category: "serif" },
      { family: "Yeseva One", category: "serif" },
      { family: "Yesteryear", category: "handwriting" },
      { family: "Yeseva One", category: "serif" },
      { family: "Yevada", category: "serif" },
      { family: "Yeseva One", category: "serif" },
      { family: "Yesteryear", category: "handwriting" },
      { family: "Yeseva One", category: "serif" },
      { family: "Yevada", category: "serif" },
      // Note: This is a subset; for full 1400+, consider loading from external JSON in future
    ];

    // Improved filtering: split query into words, match if any word is in family (case-insensitive)
    const queryWords = args.query
      .toLowerCase()
      .split(/\s+/)
      .filter((word) => word.length > 0);
    const filtered = popularFonts.filter((font) => {
      const lowerFamily = font.family.toLowerCase();
      return queryWords.some((word) => lowerFamily.includes(word));
    });

    // Sort alphabetically
    filtered.sort((a, b) => a.family.localeCompare(b.family));

    const limit = args.limit ?? 5;
    const results = filtered.slice(0, limit);
    console.log(
      `Filtered ${filtered.length} fonts for query '${args.query}', returning ${results.length}:`,
      results.map((f) => f.family)
    );

    return results;
  },
});
